#!/bin/bash

srcname=`basename $1 .qk`

python3 compiler/quack_frontend.py -i=$1 -o=asm/${srcname}.asm -c=${srcname};

if [ $? == 0 ]
then
	echo "Compiled $1 -> ${srcname}.asm";
	python3 assemble.py asm/${srcname}.asm OBJ/${srcname}.json;

	if [ $? == 0 ]
	then
		echo "Assembled ${srcname}.asm -> ${srcname}.json";
		if [ $# -eq 2 ]
		then
			bin/tiny_vm -L OBJ ${srcname}
		fi
		echo "Done";
	else
		echo "Error assembling. Aborted";
	fi
else
	echo "Error compiling. Aborted";
fi

